// Taken from https://www.w3.org/TR/wai-aria/states_and_properties#state_prop_def

export default [
  'ARIA-ACTIVEDESCENDANT', 'ARIA-ATOMIC',
  'ARIA-AUTOCOMPLETE', 'ARIA-BUSY',
  'ARIA-CHECKED', 'ARIA-CONTROLS',
  'ARIA-DESCRIBEDBY', 'ARIA-DISABLED',
  'ARIA-DROPEFFECT', 'ARIA-EXPANDED',
  'ARIA-FLOWTO', 'ARIA-GRABBED',
  'ARIA-HASPOPUP', 'ARIA-HIDDEN',
  'ARIA-INVALID', 'ARIA-LABEL',
  'ARIA-LABELLEDBY', 'ARIA-LEVEL',
  'ARIA-LIVE', 'ARIA-MULTILINE',
  'ARIA-MULTISELECTABLE', 'ARIA-ORIENTATION',
  'ARIA-OWNS', 'ARIA-POSINSET',
  'ARIA-PRESSED', 'ARIA-READONLY',
  'ARIA-RELEVANT', 'ARIA-REQUIRED',
  'ARIA-SELECTED', 'ARIA-SETSIZE',
  'ARIA-SORT', 'ARIA-VALUEMAX',
  'ARIA-VALUEMIN', 'ARIA-VALUENOW',
  'ARIA-VALUETEXT'
];
