name: 'Tests: node.js'

on: [pull_request, push]

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      latest: ${{ steps.set-matrix.outputs.requireds }}
    steps:
      - uses: ljharb/actions/node/matrix@main
        id: set-matrix
        with:
          versionsAsRoot: true
          type: 'majors'
          preset: '^20.18 || ^22.10 || >= 23'

  latest:
    needs: [matrix]
    name: 'latest majors'
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: ${{ fromJson(needs.matrix.outputs.latest) }}
        eslint:
          - 9
          - 8

    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0
      - uses: ljharb/actions/node/install@main
        name: 'nvm install ${{ matrix.node-version }} && npm install'
        env:
          NPM_CONFIG_LEGACY_PEER_DEPS: true
        with:
          after_install: npm install --no-save "eslint@${{ matrix.eslint }}"
          node-version: ${{ matrix.node-version }}
          skip-ls-check: true
      - run: npm run tests-only
      - uses: codecov/codecov-action@v3.1.5

  node:
    name: 'node 20+'
    needs: [latest]
    runs-on: ubuntu-latest
    steps:
      - run: true
